#!/bin/bash

# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
    colorflag="--color"
else # OS X `ls`
    colorflag="-G"
fi

# List all files colorized
alias ls="ls ${colorflag}"

# List all files colorized in long format
alias l="ls -hl ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -hla ${colorflag}"

alias grep='grep --color=auto --color=always'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Docker
alias compose='docker-compose'
