#!/bin/bash

# bash_profile
source $HOME/.bash_local    # Local and private settings not under version control (e.g. git credentials)

declare -a files=(
    $DOTFILES_HOME/bash/bash_options     # Options
    $DOTFILES_HOME/bash/bash_exports     # Exports
    $DOTFILES_HOME/bash/bash_aliases     # Aliases
    $DOTFILES_HOME/bash/bash_aliases_osx # Aliases
    $DOTFILES_HOME/bash/bash_prompt      # Custom bash prompt
    $DOTFILES_HOME/bash/bash_paths       # Path modifications
    $DOTFILES_HOME/bash/bash_fun         # Fun stuff :p
    $(brew --prefix nvm)/nvm.sh
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# Only use `brew` after it has been added to the PATH
bash_completion_path="/opt/local/etc/bash_completion"

# Source Bash completion (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi
