#!/bin/bash

# bash_profile

declare -a files=(
    $HOME/.dotfiles/bash/bash_options     # Options
    $HOME/.dotfiles/bash/bash_exports     # Exports
    $HOME/.dotfiles/bash/bash_aliases     # Aliases
    $HOME/.dotfiles/bash/bash_aliases_osx # Aliases
    $HOME/.dotfiles/bash/functions/*      # Functions
    $HOME/.dotfiles/bash/bash_prompt      # Custom bash prompt
    $HOME/.bash_profile.local             # Local and private settings not under version control (e.g. git credentials)
    $HOME/.dotfiles/bash/bash_paths       # Path modifications 
    $HOME/.dotfiles/bash/bash_fun         # Fun stuff :p
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# Only use `brew` after it has been added to the PATH
bash_completion_path="/opt/local/etc/bash_completion"

# Source Bash completion (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi
